### ISSUE TITLE
nesting of if-statements inside a delimitedvalues validation

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/dwca-validator#16]
Currently, the usage of an `if` validation inside a  `delimitedvalues` validation is not supported. This is because the `delimitedvalues` will use a child instance of the validator with only the individual values of the delimiter as input document of the child instance. Hence, dependency (reference inside `if` towards other fields/terms) is no longer possible in the child instance.

**Comment by stijnvanhoey** [comment]
The other way around, when an if-statement for a term refers to validations that would be referred on the individual members of a `delimitedvalues` is not possible, is something I would not support, since it would bring strange questions about aggregation. Consider the following example:

```
lifestage:
    if:
        age:
            max: 20
            type: integer
            coerce: !!python/name:int
        allowed: [juvenile]
age:
    delimitedvalues:
        delimiter: " | "
        type: integer
```
And the document would be `document = {'age' : '5 | 18 | 25', 'lifestage':'adult'}`. How should this be handled, since the condition is valid for 2 out of the 3 members of the delimitedvalues.

**Comment by stijnvanhoey** [comment]
Update: The following is actually supported:

```
age:
    delimitedvalues:
        delimiter: " | "
        if:
            lifestage:
                allowed: [juvenile]
            max: 20
lifestage:
    allowed: [juvenile, adult]
```

Which results in an `if` test for each of the delimited values. So the document: `document = {'age': '50 | 32', 'lifestage': 'juvenile'}` will result in the following error message (json-format):
```
{'age': [{0: [{'if': ['max value is 20']}],
             1: [{'if': ['max value is 20']}]}]}
```
The other way around, for which an if-condition refers to a delimited values field, is out of scope.
