### ISSUE TITLE
Type is reserved

### ISSUE THREAD

**Issue by peterdesmet** [inbo/dwca-validator#20]
The way if statements are constructed, we might run into trouble with reserved words for tests, like `type` (which is a test and DwC term). E.g.:

```YAML
basisOfRecord:
  if:
    - type: # A term
        allowed: Event
      allowed: HumanObservation
      type: string # A test
```

Gets translated as:

```JSON
{
  "basisOfRecord": {
    "if": [
      {
        "type": "string", 
        "allowed": "HumanObservation"
      }
    ]
  }
}```

**Comment by peterdesmet** [comment]
Updated example to a more logical one.

**Comment by stijnvanhoey** [comment]
This problem is similar to issue #17, resulting in similar keys, which can not be handled by a dictionary.

**Comment by peterdesmet** [comment]
Potential solutions.

## `term` and `then`

* 👍  `if` does not require a `-`
* 👎  Odd that `then` is not on the same level as `if`.
* 👎  `then` cannot be used as a term name, as it is on the same level where term names are expected

```YAML
eventID:
  if:
    - type:
        allowed: Event
      then: # New syntax
        type: integer
        numberformat: '8.'
    - type:
        # other test
```

## `term` and `term`

* 👍  No reserved words
* 👎  Term (`eventID`) is repeated
* 👎  In interpreted format it gets confusing what term is the condition (`type`) and which one has expectations (`eventID`) as they can be ordered differently
* 👎  `if` need to be repeated
* 👎  `if` needs `-`

```YAML
eventID:
  - if:
      type:
        allowed: Event
      eventID: # Gets repeated
        type: integer
        numberformat: '8.'
  - if:
     # other test
```

## `if` and `then`

* 👍  Readable
* 👍  `then` is not reserved
* 👎  `if` needs to be repeated
* 👎  `if` really needs `-`
* 👎  Can be confusing that `then` cannot have a `-`

```YAML
eventID:
  - if:
      type:
        allowed: Event
    then: # new syntax
      type: integer
      numberformat: '8.'
  - if: # repeated
     type:
        # other test
```

## `expect` and `when`

Very similar to above, but slightly improved

* 👍  All tests have `-` and have thus a defined order
* 👍  Readable
* 👍  `when` is not reserved
* 👎  `expect` needs to be repeated

```YAML
eventID:
- empty: true
- expect:
    type: integer 
    numberformat: '8.'
  when:
    type:
      allowed: Event
- expect:
    # other test
```
